# Jinja variables help maintain the recipe as you'll update the version only here.
{% set version = "2.11" %}

package:
    name: jansson
    version: {{ version }}

source:
    fn: jansson-{{ version }}.tar.gz
    url: http://www.digip.org/jansson/releases/jansson-{{ version }}.tar.gz
    sha1: 0c99636416499960214ce6c095d26af541d3c244

build:
    number: 1000

requirements:
    build:
        - cmake
        - compiler('c')
        - compiler('cxx')

test:
    commands:
        - test -f ${PREFIX}/lib/libjansson.a  # [unix]

about:
    home: https://github.com/akheron/jansson
    license: MIT
    summary: 'Jansson is a C library for encoding, decoding and manipulating JSON data.'

extra:
    recipe-maintainers:
        - mariusvniekerk
