{% set version = "2.13.1" %}

package:
  name: jansson
  version: {{ version }}

source:
  url: https://github.com/akheron/jansson/archive/v{{ version }}.tar.gz
  sha256: f22901582138e3203959c9257cf83eba9929ac41d7be4a42557213a22ebcc7a0

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('jansson', max_pin='x') }}

requirements:
  build:
    - automake  # [not win]
    - autoconf  # [not win]
    - libtool   # [not win]
    - make      # [not win]
    - autotools_clang_conda  # [win]
    - {{ compiler('c') }}
  host:

test:
  commands:
    - test ! -f ${PREFIX}/lib/libjansson.a  # [unix]
    - test -f ${PREFIX}/lib/libjansson${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/akheron/jansson
  license: MIT
  license_file: LICENSE
  summary: 'Jansson is a C library for encoding, decoding and manipulating JSON data.'

extra:
  recipe-maintainers:
    - mariusvniekerk
    - xhochy
