# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "bi4L65YWfCJfo+AUgo4FJSF4KC9R1mNFIvKWBMqCD6MqZQjiZl3Q+NJb1G1rhsVlZ1LTVxqH/5IEFcmJYzesDasnIA//Hd2yan25ptKaVpoZyBXiyir8R2ixkz00c22CxPa8o4nC29yz5uTAldFavOp9cxfSWPGiAbVePQIcL1pPjvzu7jQ/PPQJNOFtNYNhae6HTYZ5uBwQPP9SwP8m/dJxcKWU/dJqh4xGC+dIDNwJxKWFFR7SOyexCR0Q2SSiHxzqbYdwLp0cLImEu6/oivNikCASJDCUF5DPq5rlkd4AT6u4XRkOyjXc1ATSIfg9q9etJSUwwQILDYqvsPCEu0nds8wjG+8+VIl37GE+Z0a8PkAQC/axJwFC8BbE1NwVzBfMd5DuHeNtB6IYTvAcdFyi1wnJKqlptMFF+ysuzklV7ZlEBaaAwCvH+JwPtSUjCf38bKt2NyIRKEiqGQHYGaSPSIRS1H8N8MsnPK4BElwM1zbMgaqLUshJi9MP8aezAA7fy0fj388+9AzWs2jzbIstH9ZESyLv9JOuFDIxu3l2xrbuTY2XqX3KU6wpfOsjOyKcsHx2wtsRG6hzcIJ1INRl0d9ZtN3BSli/NzCxUHgE+csPp8RtsOBJZa5XPqivJDUO1V3mDZuWvfcPyiKgM9xSNyYwhowrY+3Ygfr8bLU="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
