travis:
  secure:
    BINSTAR_TOKEN: 12nfwr2htD/F+JRCg2xcq/wp42WKGC4J/6KJ9ygW2prboUPqm9UrqYD4Eftid1cJM510j3g4a7bQFqrokcMuYwYPrdMejp3vZ71NCmpjZH90MErFjAga5fDZjbTl7Vi+uo4REWeLpy9pZDTS6k8zWDcYV1GVkhhYbO/txCPxsvUxptfgflwG8gG1T+ourIB2K0lRanTBUWLUSYW4rTB8jYoeW9M9ttF7ydZXVicHSfSdv0yP5S4Krc5gm8V2zNouISbz2a0Rb9PH4tnS212ty6RfF9alO6+hT+O9WJbF5nfjnlgg/prw2PlWNp7Z9nHH67cyg7KktxXzhc7TuQuSpGohXdo98QJDeRPPataackKY6kRRxki2KaO0z8uNU6BuU7hwt6KCgAaZrGNw6J9KszHp50fbA+k2+55XEQ+QOjDawkaf1YM9PJnGMsb+vLsWdswTE1kfHcYE6hZF7EIlOULTE17ObH/2lfttm1ifBPTIi8dxVxuMIerwxCPI04lMJeb723G9wDBpocdMvrB+Xe2ajXbzSrpVWGn7KnMzKX0CgV70M4CXFB2QP7Y2POzYj3Vj/g/pio76atmcAGUxl6/PVZ0M3V6A+jPIWNrwldQlaAN047RvivMItHzrXEpgU6IPeKAT12JhNfH5tJtkfbStI+RfCcEqXr4yNY2iLC4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
