travis:
  secure:
    BINSTAR_TOKEN: bi4L65YWfCJfo+AUgo4FJSF4KC9R1mNFIvKWBMqCD6MqZQjiZl3Q+NJb1G1rhsVlZ1LTVxqH/5IEFcmJYzesDasnIA//Hd2yan25ptKaVpoZyBXiyir8R2ixkz00c22CxPa8o4nC29yz5uTAldFavOp9cxfSWPGiAbVePQIcL1pPjvzu7jQ/PPQJNOFtNYNhae6HTYZ5uBwQPP9SwP8m/dJxcKWU/dJqh4xGC+dIDNwJxKWFFR7SOyexCR0Q2SSiHxzqbYdwLp0cLImEu6/oivNikCASJDCUF5DPq5rlkd4AT6u4XRkOyjXc1ATSIfg9q9etJSUwwQILDYqvsPCEu0nds8wjG+8+VIl37GE+Z0a8PkAQC/axJwFC8BbE1NwVzBfMd5DuHeNtB6IYTvAcdFyi1wnJKqlptMFF+ysuzklV7ZlEBaaAwCvH+JwPtSUjCf38bKt2NyIRKEiqGQHYGaSPSIRS1H8N8MsnPK4BElwM1zbMgaqLUshJi9MP8aezAA7fy0fj388+9AzWs2jzbIstH9ZESyLv9JOuFDIxu3l2xrbuTY2XqX3KU6wpfOsjOyKcsHx2wtsRG6hzcIJ1INRl0d9ZtN3BSli/NzCxUHgE+csPp8RtsOBJZa5XPqivJDUO1V3mDZuWvfcPyiKgM9xSNyYwhowrY+3Ygfr8bLU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
